name: create_flutter_app
description: A CLI to scaffold Flutter projects with customizable setup.
version: 0.0.1
homepage: https://github.com/ani-sh-arma/create_flutter_app
repository: https://github.com/ani-sh-arma/create_flutter_app

environment:
  sdk: ^3.7.2

executables:
  create_flutter_app:

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  prompts: ^2.0.0
  ansicolor: ^2.0.3
